package tech.hearth.state

import tech.hearth.account.Address
import tech.hearth.transaction.BlockchainUpdater

class ForwardingBlockchainUpdaterImpl(delegate: CompleteBlockchainUpdater) extends Blockchain with BlockchainUpdater with NG {
  export delegate.{
    settings,
    height,
    finalizedHeight,
    finalizedHeightAt,
    score,
    blockHeader,
    hitSource,
    carryFee,
    heightOf,
    approvedFeatures,
    activatedFeatures,
    featureVotes,
    blockReward,
    hearthAmount,
    transactionInfo,
    transactionInfos,
    transactionMeta,
    transactionSnapshot,
    containsTransaction,
    assetDescription,
    leaseDetails,
    dcapRootCaCrl,
    dcapPckCrl,
    dcapTcbInfo,
    dcapQeIdentity,
    dcapTcbSigningIssuerChain,
    filledVolumeAndFee,
    balanceAtHeight,
    balanceSnapshots,
    leaseBalance,
    leaseBalances,
    balance,
    balances,
    hearthBalances,
    effectiveBalanceBanHeights,
    lastStateHash,
    processBlock,
    processMicroBlock,
    computeNextReward,
    removeAfter,
    lastBlockInfo,
    isLastBlockId,
    referencedBlockchain,
    shutdown,
    microBlock,
    bestLastBlockInfo,
    microblockIds,
    liquidBlock,
    liquidBlockSnapshot,
    microBlockSnapshot,
    liquidTransactions,
    liquidBlockMeta,
    bestLiquidSnapshot,
    bestLiquidSnapshotAndFees,
    snapshotBlockchain,
    currentGeneratorSet,
    conflictGenerators
  }

  override def committedGenerators(at: GenerationPeriod): IndexedSeq[CommittedGenerator] = delegate.committedGenerators(at)
}
