package tech.hearth.state

import tech.hearth.test.PropSpec
import org.scalacheck.Gen

/** `Mainnet`/`Testnet`/`Stagenet` `R0`/`Ratio` are the real per-network S2.4 constants: derived offline (see the
  * derivation note on `RewardsSettings`), not re-derived here. This file's vectors are the Scala-side half of the
  * cross-language reproducibility contract for a future non-JVM client (`node-jvm` implies at least one is coming;
  * a Go port is in progress as of this writing): every one of them is transcribed from, and must stay in sync with,
  * `hearth-specs/emission-curve/vectors.json` (https://github.com/hearth-chain/hearth-specs, a sibling repo - not a
  * build dependency of this one), generated by that repo's `derive.py`. Any correct implementation of the same
  * fixed-point algorithm against the same literal constants must reproduce every one of these exact ember counts;
  * if a formula or a network's parameters ever change, regenerate `vectors.json` there first and re-transcribe here,
  * not the other way around.
  */
class EmissionCurveTest extends PropSpec {

  private val OneScaled = BigInt(1) << EmissionCurve.FixedPointBits

  private val BlocksPerYear = 525600L

  private val MainnetR0             = 1252834433L
  private val MainnetRatio          = BigInt("340282322045415694657836056900309514630")
  private val MainnetHalfLifeBlocks = 5256000L

  // TESTNET and STAGENET are configured identically (1-year half-life, same cEmit), so their vectors coincide;
  // both are kept here so a change to either network's parameters is caught by name.
  private val TestnetR0             = 12528336897L
  private val TestnetRatio          = BigInt("340281918165977088157076486680406733895")
  private val TestnetHalfLifeBlocks = 525600L

  private val StagenetR0             = 12528336897L
  private val StagenetRatio          = BigInt("340281918165977088157076486680406733895")
  private val StagenetHalfLifeBlocks = 525600L

  property("reward at h=0 equals the initial reward exactly") {
    EmissionCurve.rewardAt(0, initialReward = MainnetR0, decayRatioFixed = OneScaled) shouldBe MainnetR0
    // h = 0 is the *first rewarded block* (chain height 2), not genesis - so the very first reward is R0 itself,
    // and any emission total that starts the sum at h = 1 is short by exactly R0.
    EmissionCurve.rewardAt(0, MainnetR0, MainnetRatio) shouldBe MainnetR0
  }

  property("reward matches the spec's illustrative year table (S2.4)") {
    val yearToReward = Seq(
      1  -> 1168935858L,
      2  -> 1090655721L,
      4  -> 949470952L,
      8  -> 719564426L,
      12 -> 545327860L,
      20 -> 313208608L,
      40 -> 78302152L
    )

    yearToReward.foreach { case (years, expectedEmbers) =>
      withClue(s"year $years: ") {
        EmissionCurve.rewardAt(years * BlocksPerYear, MainnetR0, MainnetRatio) shouldBe expectedEmbers
      }
    }
  }

  property("reward at exactly one half-life, every network") {
    // decayRatioFixed is a *rounded* approximation of the true irrational ratio, so the fixed-point result at
    // h=halfLifeBlocks can land a handful of embers either side of the idealized R0/2 - these are the actual,
    // correct values (hearth-specs/emission-curve/vectors.json), not a theoretical exact half.
    val networkToHalfLifeReward = Seq(
      (MainnetR0, MainnetRatio, MainnetHalfLifeBlocks)    -> 626417216L,
      (TestnetR0, TestnetRatio, TestnetHalfLifeBlocks)    -> 6264168448L,
      (StagenetR0, StagenetRatio, StagenetHalfLifeBlocks) -> 6264168448L
    )

    networkToHalfLifeReward.foreach { case ((r0, ratio, halfLife), expected) =>
      EmissionCurve.rewardAt(halfLife, r0, ratio) shouldBe expected
    }
  }

  property("reward never increases block over block") {
    forAll(Gen.choose(0L, 50 * BlocksPerYear)) { h =>
      val current = EmissionCurve.rewardAt(h, MainnetR0, MainnetRatio)
      val next    = EmissionCurve.rewardAt(h + 1, MainnetR0, MainnetRatio)
      next should be <= current
    }
  }

  property("reward underflows to exactly zero, never negative, arbitrarily far past the cap's asymptote") {
    EmissionCurve.rewardAt(1000 * MainnetHalfLifeBlocks, MainnetR0, MainnetRatio) shouldBe 0L
    EmissionCurve.rewardAt(1000 * TestnetHalfLifeBlocks, TestnetR0, TestnetRatio) shouldBe 0L
    EmissionCurve.rewardAt(1000 * StagenetHalfLifeBlocks, StagenetR0, StagenetRatio) shouldBe 0L
  }

  property("rejects a negative height") {
    an[IllegalArgumentException] should be thrownBy EmissionCurve.rewardAt(-1, MainnetR0, MainnetRatio)
  }

  property("powFixed identities") {
    EmissionCurve.powFixed(MainnetRatio, 0) shouldBe OneScaled
    EmissionCurve.powFixed(MainnetRatio, 1) shouldBe MainnetRatio
    EmissionCurve.powFixed(OneScaled, 999999999L) shouldBe OneScaled
  }
}
