hearth {
  db {
    directory = ${?hearth.data-directory}
    max-rollback-depth = ${?hearth.max-rollback-depth}
    max-cache-size = ${?hearth.max-cache-size}
    remember-blocks = ${?hearth.remember-blocks-interval-in-cache}
  }
}

pekko.http.server {
  idle-timeout = ${?akka.http.server.idle-timeout}
  request-timeout = ${?akka.http.server.request-timeout}
}
