package tech.hearth.database

import com.google.common.primitives.Shorts

enum KeyTag {
  case Version,
    Height,
    HeightOf,
    HearthBalance,
    HearthBalanceHistory,
    AssetBalanceHistory,
    AssetBalance,
    AssetVolumeDetailsHistory,
    AssetVolumeDetails,
    LeaseBalanceHistory,
    LeaseBalance,
    LeaseDetailsHistory,
    LeaseDetails,
    FilledVolumeAndFeeHistory,
    FilledVolumeAndFee,
    ChangedAddresses,
    ChangedHearthBalances,
    ChangedAssetBalances,
    ChangedDataKeys,
    AddressIdOfAlias,
    LastAddressId,
    AddressId,
    IdToAddress,
    AddressScriptHistory,
    AddressScript,
    ApprovedFeatures,
    ActivatedFeatures,
    DataHistory,
    Data,
    AssetMinFeeHistory,
    AssetMinFee,
    CarryFee,
    AssetScriptHistory,
    AssetScript,
    SafeRollbackHeight,
    LastCleanupHeight,
    BlockInfoAtHeight,
    NthTransactionInfoAtHeight,
    AddressTransactionSeqNr,
    AddressTransactionHeightTypeAndNums,
    TransactionMetaById,
    InvokeScriptResult,
    DisabledAliases,
    AssetStaticInfo,
    NftCount,
    NftPossession,
    IssuedAssets,
    UpdatedAssets, // retired: always identical to IssuedAssets once asset info became immutable after issuance;
    // left in place (rather than removed) to avoid shifting every later ordinal's on-disk prefix
    AssetsWithMinFee,
    StateHash,
    EthereumTransactionMeta,
    NthTransactionStateSnapshotAtHeight,
    MaliciousMinerBanHeights,
    BlockStateHash,
    AddressLeaseInfoSeqNr,
    AddressLeaseInfoSeq,
    FinalizedBlockHeight,
    FinalizedBlockHeightAt,
    CommittedGenerators,
    ConflictGenerators,
    CommitmentTransactions,
    GeneratorBalances,
    DcapRootCaCrlHistory,
    DcapRootCaCrl,
    DcapPckCrlHistory,
    DcapPckCrl,
    DcapTcbInfoHistory,
    DcapTcbInfo,
    DcapQeIdentityHistory,
    DcapQeIdentity,
    DcapTcbSigningIssuerChainHistory,
    DcapTcbSigningIssuerChain,
    DcapTcbInfoFmspcsAtHeight,
    DcapPckCaIssuerChainHistory,
    DcapPckCaIssuerChain,
    RegisteredEnclaves,
    ReservedAmountHistory,
    ReservedAmount,
    ReservedAmountKeysAtHeight,
    ApiKeyBindingHistory,
    ApiKeyBinding,
    ApiKeyBindingKeysAtHeight

  def prefixBytes: Array[Byte] = Shorts.toByteArray(ordinal.toShort)
}
