package tech.hearth.database

import com.google.common.primitives.Shorts

enum KeyTag {
  case Version,
    Height,
    HeightOf,
    HearthBalance,
    HearthBalanceHistory,
    AssetBalanceHistory,
    AssetBalance,
    AssetVolumeDetailsHistory,
    AssetVolumeDetails,
    LeaseBalanceHistory,
    LeaseBalance,
    LeaseDetailsHistory,
    LeaseDetails,
    FilledVolumeAndFeeHistory,
    FilledVolumeAndFee,
    ChangedAddresses,
    ChangedHearthBalances,
    ChangedAssetBalances,
    ChangedDataKeys,
    AddressIdOfAlias,
    LastAddressId,
    AddressId,
    IdToAddress,
    AddressScriptHistory,
    AddressScript,
    ApprovedFeatures,
    ActivatedFeatures,
    DataHistory,
    Data,
    AssetMinFeeHistory,
    AssetMinFee,
    CarryFee,
    AssetScriptHistory,
    AssetScript,
    SafeRollbackHeight,
    LastCleanupHeight,
    BlockInfoAtHeight,
    NthTransactionInfoAtHeight,
    AddressTransactionSeqNr,
    AddressTransactionHeightTypeAndNums,
    TransactionMetaById,
    InvokeScriptResult,
    DisabledAliases,
    AssetStaticInfo,
    NftCount,
    NftPossession,
    IssuedAssets,
    // Was UpdatedAssets, retired when asset info became immutable after issuance (it was then always identical to
    // IssuedAssets). Immutable is no longer true - a predefined snapshot can re-issue an existing asset - so the
    // ordinal is reused rather than appending a new one. Nothing this fork ever ran wrote under it.
    AssetsWithUpdatedVolume,
    AssetsWithMinFee,
    StateHash,
    EthereumTransactionMeta,
    NthTransactionStateSnapshotAtHeight,
    MaliciousMinerBanHeights,
    BlockStateHash,
    AddressLeaseInfoSeqNr,
    AddressLeaseInfoSeq,
    FinalizedBlockHeight,
    FinalizedBlockHeightAt,
    CommittedGenerators,
    ConflictGenerators,
    CommitmentTransactions,
    GeneratorBalances,
    DcapRootCaCrlHistory,
    DcapRootCaCrl,
    DcapPckCrlHistory,
    DcapPckCrl,
    DcapTcbInfoHistory,
    DcapTcbInfo,
    DcapQeIdentityHistory,
    DcapQeIdentity,
    DcapTcbSigningIssuerChainHistory,
    DcapTcbSigningIssuerChain,
    DcapTcbInfoFmspcsAtHeight,
    DcapPckCaIssuerChainHistory,
    DcapPckCaIssuerChain,
    RegisteredEnclaves,
    ReservedAmountHistory,
    ReservedAmount,
    ReservedAmountKeysAtHeight,
    ApiKeyBindingHistory,
    ApiKeyBinding,
    ApiKeyBindingKeysAtHeight,
    SettledAmountHistory,
    SettledAmount,
    SettledAmountKeysAtHeight,
    WorkDoneHistory,
    WorkDone,
    WorkDoneKeysAtHeight

  def prefixBytes: Array[Byte] = Shorts.toByteArray(ordinal.toShort)
}
