package tech.hearth.history

import tech.hearth.*
import tech.hearth.db.WithState.AddrWithBalance
import tech.hearth.test.{PropSpec, produce}
import tech.hearth.transaction.TxHelpers
import org.scalatest.*

class BlockchainUpdaterKeyAndMicroBlockConflictTest extends PropSpec with DomainScenarioDrivenPropertyCheck with OptionValues {

  private val FeeAmount      = 400000L
  private val TransferAmount = FeeAmount * 10

  // Blocks are built through the domain: they have to be generated by a committed generator, carry a VRF proof by the
  // key it committed and a computed state hash, none of which a hand-rolled block builder supplies.
  property("new key block should be validated to previous") {
    forAll(accountGen, accountGen) { (richAccount, secondAccount) =>
      withDomain(MicroblocksActivatedAt0HearthSettings, Seq(AddrWithBalance(richAccount.toAddress, TransferAmount + FeeAmount))) { d =>
        val transfer1 = TxHelpers.transfer(richAccount, secondAccount.toAddress, TransferAmount, fee = FeeAmount)
        // Everything the second account has, twice over: only one of the two can be in the state
        val transfer2 = TxHelpers.transfer(secondAccount, richAccount.toAddress, TransferAmount - FeeAmount, fee = FeeAmount)
        val transfer3 = TxHelpers.transfer(secondAccount, richAccount.toAddress, TransferAmount - FeeAmount, fee = FeeAmount)

        val keyBlock = d.createBlock(Seq(transfer1))
        d.appendBlock(keyBlock)

        // Built while the key block is still the head, so its state hash is the one that block leads to - the micro
        // block below is applied on top of the same key block, on the branch this one does not take
        val competingKeyBlock = d.createBlock(Seq(transfer3), ref = Some(keyBlock.id()))

        d.appendMicroBlock(transfer2)

        d.appendBlockE(competingKeyBlock) should beRight
      }
    }
  }

  property("a key block that references the liquid block sees the transactions of its micro blocks") {
    forAll(accountGen, accountGen) { (richAccount, secondAccount) =>
      withDomain(MicroblocksActivatedAt0HearthSettings, Seq(AddrWithBalance(richAccount.toAddress, TransferAmount + FeeAmount))) { d =>
        val transfer1 = TxHelpers.transfer(richAccount, secondAccount.toAddress, TransferAmount, fee = FeeAmount)
        val transfer2 = TxHelpers.transfer(secondAccount, richAccount.toAddress, TransferAmount - FeeAmount, fee = FeeAmount)
        val transfer3 = TxHelpers.transfer(secondAccount, richAccount.toAddress, TransferAmount - FeeAmount, fee = FeeAmount)

        d.appendBlock(transfer1)
        d.appendMicroBlock(transfer2)

        // The other side of the property above: on top of the liquid block the micro block's transfer is part of the
        // state, and it left the second account with nothing to spend
        d.appendBlockE(transfer3) should produce("negative hearth balance")
      }
    }
  }

  property("effective balance is validated against the referenced block") {
    forAll(accountGen, accountGen, accountGen) { (richAccount, secondAccount, randomAccount) =>
      withDomain(MicroblocksActivatedAt0HearthSettings, Seq(AddrWithBalance(richAccount.toAddress, TransferAmount + FeeAmount * 3))) { d =>
        val lease       = TxHelpers.lease(richAccount, secondAccount.toAddress, TransferAmount, fee = FeeAmount)
        val leaseCancel = TxHelpers.leaseCancel(lease.id(), richAccount, fee = FeeAmount)
        val transfer    = TxHelpers.transfer(richAccount, randomAccount.toAddress, TransferAmount, fee = FeeAmount)

        d.appendBlock(lease)
        val leaseBlockId = d.lastBlockId

        val keyBlock = d.createBlock(Nil)
        d.appendBlock(keyBlock)
        d.blockchainUpdater.effectiveBalance(secondAccount.toAddress, 0) should be > 0L

        d.appendMicroBlock(leaseCancel)
        d.blockchainUpdater.effectiveBalance(secondAccount.toAddress, 0, Some(leaseBlockId)) should be > 0L

        // The transfer block references the key block, where the lease is still in force, so the rich account cannot
        // move what it has leased out - the micro block that cancelled the lease is not on that branch
        d.appendBlockE(d.createBlock(Seq(transfer), ref = Some(keyBlock.id()))) should produce("negative effective balance")
      }
    }
  }
}
