name: Prepare release draft
run-name: Prepare release draft for ${{ inputs.version }} from ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      networks:
        description: 'Networks'
        required: true
        default: 'mainnet testnet stagenet'
      version:
        description: 'Version'
        required: true

jobs:
  prepare-release-draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'sbt'
      - uses: sbt/setup-sbt@bfea3c5f48abd221b04a6df4798aa5eb8b6a2baf # v1.5.6
      - run: ./.github/workflows/prepare-release-draft.sh
        id: prepare-release-draft
        env:
          RELEASE_VERSION: ${{ inputs.version }}
          RELEASE_NETWORKS: ${{ inputs.networks }}
          RELEASE_BRANCH: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPO: ${{ github.repository }}
      - uses: actions/attest-build-provenance@0f67c3f4856b2e3261c31976d6725780e5e4c373 # v4.1.1
        with:
          subject-path: ${{ steps.prepare-release-draft.outputs.subject-path }}
